apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart
  name: cart
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: cart
  sessionAffinity: None
  type: ClusterIP