apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
  name: catalog
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: catalog
  sessionAffinity: None
  type: ClusterIP