apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
  namespace: default
spec:
  ports:
    - port: 8900
      protocol: TCP
      targetPort: 8900
  selector:
    app: auth
  sessionAffinity: None
  type: ClusterIP