apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Порт, на котором работает KrakenD в контейнере
  type: LoadBalancer