apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discovery
  name: discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - image: maxawergy/discovery-service:latest
          imagePullPolicy: Never
          name: discovery
          resources:
            limits:
              cpu: "0.5"
              memory: "500M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always