apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
  name: config
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - image: maxawergy/config-service:latest
          imagePullPolicy: Never
          name: config
          resources:
            limits:
              cpu: "0.5"
              memory: "500M"
      dnsPolicy: ClusterFirst
      restartPolicy: Always