apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    max_connections = 100
    shared_buffers = 256MB
    effective_cache_size = 2GB
    maintenance_work_mem = 128MB
    checkpoint_timeout = 5min
    wal_level = replica
    archive_mode = off
    listen_addresses = '*'
  pg_hba.conf: |
    # "local" - Для соединений совершенных из того же хоста
    local   all             all                                     md5
    # IPv4 - Для локальных соединений
    host    all             all             127.0.0.1/32            md5
    # IPv4 - Для соединений с других хостов
    host    all             all             0.0.0.0/0               md5
    # IPv6 - Для локальных соединений
    host    all             all             ::1/128                 md5
    # IPv6 - Для соединений с других хостов
    host    all             all             ::/0                    md5