apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
  namespace: default
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: order
  sessionAffinity: None
  type: ClusterIP